add_test( IntPoint.ConstructorTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.GetXTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.GetXTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.GetXTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.GetYTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.GetYTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.GetYTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.StringTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.EqualTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.NotEqualTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.CopyTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.CopyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.CopyTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.AddTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.AddTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.AddTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.SubstTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.SubstTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.SubstTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntPoint.ScaleTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=IntPoint.ScaleTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntPoint.ScaleTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.ConstructorTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.GetXTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.GetXTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.GetXTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.GetYTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.GetYTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.GetYTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.StringTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.EqualTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.NotEqualTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.CopyTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.CopyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.CopyTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.AddTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.AddTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.AddTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.SubstTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.SubstTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.SubstTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPoint.ScaleTest /home/sebastolmos/projects/octagram/bin/PointClassTests [==[--gtest_filter=FloatPoint.ScaleTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPoint.ScaleTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( PointClassTests_TESTS IntPoint.ConstructorTest IntPoint.GetXTest IntPoint.GetYTest IntPoint.StringTest IntPoint.EqualTest IntPoint.NotEqualTest IntPoint.CopyTest IntPoint.AddTest IntPoint.SubstTest IntPoint.ScaleTest FloatPoint.ConstructorTest FloatPoint.GetXTest FloatPoint.GetYTest FloatPoint.StringTest FloatPoint.EqualTest FloatPoint.NotEqualTest FloatPoint.CopyTest FloatPoint.AddTest FloatPoint.SubstTest FloatPoint.ScaleTest)
