add_test( intPolygon.ConstructorTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.addPointTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.addPointTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.addPointTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.StringTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.getAreaTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.getAreaTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.getAreaTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.getAreaTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.getAreaTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.getAreaTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.getAreaTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.getAreaTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.getAreaTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.CCWTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.CCWTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.CCWTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.CCWTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.CCWTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.CCWTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.CCWTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.CCWTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.CCWTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.BorderTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.BorderTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.BorderTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.InsideTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.InsideTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.InsideTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.InsideTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.InsideTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.InsideTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.InsideTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.InsideTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.InsideTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.EqualTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.EqualTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.EqualTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.EqualTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.EqualTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.EqualTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.NotEqualTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.NotEqualTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.NotEqualTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( intPolygon.NotEqualTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=intPolygon.NotEqualTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( intPolygon.NotEqualTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.ConstructorTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.addPointTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.addPointTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.addPointTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.StringTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.getAreaTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.getAreaTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.getAreaTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.getAreaTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.getAreaTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.getAreaTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.getAreaTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.getAreaTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.getAreaTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.CCWTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.CCWTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.CCWTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.CCWTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.CCWTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.CCWTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.CCWTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.CCWTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.CCWTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.BorderTest /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.BorderTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.BorderTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.InsideTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.InsideTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.InsideTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.InsideTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.InsideTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.InsideTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.InsideTest3 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.InsideTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.InsideTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.EqualTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.EqualTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.EqualTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.EqualTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.EqualTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.EqualTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.NotEqualTest1 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.NotEqualTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.NotEqualTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatPolygon.NotEqualTest2 /home/sebastolmos/projects/octagram/bin/PolygonClassTests [==[--gtest_filter=FloatPolygon.NotEqualTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatPolygon.NotEqualTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( PolygonClassTests_TESTS intPolygon.ConstructorTest intPolygon.addPointTest intPolygon.StringTest intPolygon.getAreaTest1 intPolygon.getAreaTest2 intPolygon.getAreaTest3 intPolygon.CCWTest1 intPolygon.CCWTest2 intPolygon.CCWTest3 intPolygon.BorderTest intPolygon.InsideTest1 intPolygon.InsideTest2 intPolygon.InsideTest3 intPolygon.EqualTest1 intPolygon.EqualTest2 intPolygon.NotEqualTest1 intPolygon.NotEqualTest2 FloatPolygon.ConstructorTest FloatPolygon.addPointTest FloatPolygon.StringTest FloatPolygon.getAreaTest1 FloatPolygon.getAreaTest2 FloatPolygon.getAreaTest3 FloatPolygon.CCWTest1 FloatPolygon.CCWTest2 FloatPolygon.CCWTest3 FloatPolygon.BorderTest FloatPolygon.InsideTest1 FloatPolygon.InsideTest2 FloatPolygon.InsideTest3 FloatPolygon.EqualTest1 FloatPolygon.EqualTest2 FloatPolygon.NotEqualTest1 FloatPolygon.NotEqualTest2)
