add_test( IntSegment.ConstructorTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.EqualTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NotEqualTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.PointsConstructorTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.PointsConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.PointsConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.getOriginTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.getOriginTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.getOriginTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.getEndTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.getEndTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.getEndTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.setOriginTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.setOriginTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.setOriginTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.setEndTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.setEndTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.setEndTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.StringTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.getLength2Test /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.getLength2Test]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.getLength2Test PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.getLengthTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.getLengthTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.getLengthTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.leftTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.leftTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.leftTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.rigthTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.rigthTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.rigthTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.colinearTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.colinearTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.colinearTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.IntersectionTest1 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.IntersectionTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.IntersectionTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest1 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.IntersectionTest2 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.IntersectionTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.IntersectionTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest2 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.IntersectionTest3 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.IntersectionTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.IntersectionTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.IntersectionTest4 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.IntersectionTest4]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.IntersectionTest4 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest3 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest4 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest4]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest4 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest5 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest5]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest5 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntSegment.NonIntersectionTest6 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=IntSegment.NonIntersectionTest6]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntSegment.NonIntersectionTest6 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.ConstructorTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.EqualTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NotEqualTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.PointsConstructorTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.PointsConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.PointsConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.getOriginTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.getOriginTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.getOriginTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.getEndTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.getEndTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.getEndTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.setOriginTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.setOriginTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.setOriginTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.setEndTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.setEndTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.setEndTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.StringTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.getLength2Test /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.getLength2Test]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.getLength2Test PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.getLengthTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.getLengthTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.getLengthTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.leftTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.leftTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.leftTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.rigthTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.rigthTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.rigthTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.colinearTest /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.colinearTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.colinearTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.IntersectionTest1 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.IntersectionTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.IntersectionTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest1 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest1]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest1 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.IntersectionTest2 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.IntersectionTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.IntersectionTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest2 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest2]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest2 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.IntersectionTest3 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.IntersectionTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.IntersectionTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.IntersectionTest4 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.IntersectionTest4]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.IntersectionTest4 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest3 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest3]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest3 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest4 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest4]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest4 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest5 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest5]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest5 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatSegment.NonIntersectionTest6 /home/sebastolmos/projects/octagram/bin/SegmentClassTests [==[--gtest_filter=FloatSegment.NonIntersectionTest6]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatSegment.NonIntersectionTest6 PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( SegmentClassTests_TESTS IntSegment.ConstructorTest IntSegment.EqualTest IntSegment.NotEqualTest IntSegment.PointsConstructorTest IntSegment.getOriginTest IntSegment.getEndTest IntSegment.setOriginTest IntSegment.setEndTest IntSegment.StringTest IntSegment.getLength2Test IntSegment.getLengthTest IntSegment.leftTest IntSegment.rigthTest IntSegment.colinearTest IntSegment.IntersectionTest1 IntSegment.NonIntersectionTest1 IntSegment.IntersectionTest2 IntSegment.NonIntersectionTest2 IntSegment.IntersectionTest3 IntSegment.IntersectionTest4 IntSegment.NonIntersectionTest3 IntSegment.NonIntersectionTest4 IntSegment.NonIntersectionTest5 IntSegment.NonIntersectionTest6 FloatSegment.ConstructorTest FloatSegment.EqualTest FloatSegment.NotEqualTest FloatSegment.PointsConstructorTest FloatSegment.getOriginTest FloatSegment.getEndTest FloatSegment.setOriginTest FloatSegment.setEndTest FloatSegment.StringTest FloatSegment.getLength2Test FloatSegment.getLengthTest FloatSegment.leftTest FloatSegment.rigthTest FloatSegment.colinearTest FloatSegment.IntersectionTest1 FloatSegment.NonIntersectionTest1 FloatSegment.IntersectionTest2 FloatSegment.NonIntersectionTest2 FloatSegment.IntersectionTest3 FloatSegment.IntersectionTest4 FloatSegment.NonIntersectionTest3 FloatSegment.NonIntersectionTest4 FloatSegment.NonIntersectionTest5 FloatSegment.NonIntersectionTest6)
