add_test( IntVector.ConstructorTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.GetXTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.GetXTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.GetXTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.GetYTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.GetYTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.GetYTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.GetZTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.GetZTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.GetZTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.StringTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.EqualTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.NotEqualTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.CopyTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.CopyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.CopyTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.ConstructorPointsTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.ConstructorPointsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.ConstructorPointsTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.AddTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.AddTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.AddTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.SubstTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.SubstTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.SubstTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.ScaleTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.ScaleTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.ScaleTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.DotTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.DotTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.DotTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.CrossTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.CrossTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.CrossTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.Magnitude2Test /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.Magnitude2Test]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.Magnitude2Test PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.MagnitudeTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.MagnitudeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.MagnitudeTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.NormalizeTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.NormalizeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.NormalizeTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( IntVector.SetTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=IntVector.SetTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( IntVector.SetTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.ConstructorTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.ConstructorTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.ConstructorTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.GetXTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.GetXTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.GetXTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.GetYTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.GetYTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.GetYTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.GetZTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.GetZTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.GetZTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.StringTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.StringTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.EqualTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.EqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.EqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.NotEqualTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.NotEqualTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.NotEqualTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.CopyTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.CopyTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.CopyTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.ConstructorPointsTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.ConstructorPointsTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.ConstructorPointsTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.AddTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.AddTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.AddTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.SubstTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.SubstTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.SubstTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.ScaleTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.ScaleTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.ScaleTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.DotTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.DotTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.DotTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.CrossTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.CrossTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.CrossTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.Magnitude2Test /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.Magnitude2Test]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.Magnitude2Test PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.MagnitudeTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.MagnitudeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.MagnitudeTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.NormalizeTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.NormalizeTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.NormalizeTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FloatVector.SetTest /home/sebastolmos/projects/octagram/bin/VectorClassTests [==[--gtest_filter=FloatVector.SetTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( FloatVector.SetTest PROPERTIES WORKING_DIRECTORY /home/sebastolmos/projects/octagram/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( VectorClassTests_TESTS IntVector.ConstructorTest IntVector.GetXTest IntVector.GetYTest IntVector.GetZTest IntVector.StringTest IntVector.EqualTest IntVector.NotEqualTest IntVector.CopyTest IntVector.ConstructorPointsTest IntVector.AddTest IntVector.SubstTest IntVector.ScaleTest IntVector.DotTest IntVector.CrossTest IntVector.Magnitude2Test IntVector.MagnitudeTest IntVector.NormalizeTest IntVector.SetTest FloatVector.ConstructorTest FloatVector.GetXTest FloatVector.GetYTest FloatVector.GetZTest FloatVector.StringTest FloatVector.EqualTest FloatVector.NotEqualTest FloatVector.CopyTest FloatVector.ConstructorPointsTest FloatVector.AddTest FloatVector.SubstTest FloatVector.ScaleTest FloatVector.DotTest FloatVector.CrossTest FloatVector.Magnitude2Test FloatVector.MagnitudeTest FloatVector.NormalizeTest FloatVector.SetTest)
